---
site_name: Simple Docs
nav:
  - 'Home': './index.md'
docs_dir: docs
repo_url: https://localhost:3000/
edit_uri_template: edit/main/data/docs/simple-docs/docs/{path}
plugins:
  - techdocs-core
markdown_extensions:
  - md_in_html
